# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import agent_pb2 as proto_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """AgentService handles AI agent chat with RAG capabilities.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatCompletion = channel.unary_unary(
                '/memo.agent.AgentService/ChatCompletion',
                request_serializer=proto_dot_agent__pb2.ChatRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ChatCompletionStream = channel.unary_stream(
                '/memo.agent.AgentService/ChatCompletionStream',
                request_serializer=proto_dot_agent__pb2.ChatRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.ChatEvent.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/memo.agent.AgentService/HealthCheck',
                request_serializer=proto_dot_agent__pb2.HealthRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.HealthResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """AgentService handles AI agent chat with RAG capabilities.
    """

    def ChatCompletion(self, request, context):
        """Unary: simple request/response for non-streaming callers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatCompletionStream(self, request, context):
        """Server-streaming: token-by-token for frontend SSE.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatCompletion,
                    request_deserializer=proto_dot_agent__pb2.ChatRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.ChatResponse.SerializeToString,
            ),
            'ChatCompletionStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatCompletionStream,
                    request_deserializer=proto_dot_agent__pb2.ChatRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.ChatEvent.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_agent__pb2.HealthRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memo.agent.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memo.agent.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """AgentService handles AI agent chat with RAG capabilities.
    """

    @staticmethod
    def ChatCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memo.agent.AgentService/ChatCompletion',
            proto_dot_agent__pb2.ChatRequest.SerializeToString,
            proto_dot_agent__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatCompletionStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/memo.agent.AgentService/ChatCompletionStream',
            proto_dot_agent__pb2.ChatRequest.SerializeToString,
            proto_dot_agent__pb2.ChatEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memo.agent.AgentService/HealthCheck',
            proto_dot_agent__pb2.HealthRequest.SerializeToString,
            proto_dot_agent__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TextProcessorServiceStub(object):
    """═══════════════════════════════════════════════════════════════════════════════
    TextProcessorService — CJK-aware text tokenization and document chunking
    ═══════════════════════════════════════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Tokenize = channel.unary_unary(
                '/memo.agent.TextProcessorService/Tokenize',
                request_serializer=proto_dot_agent__pb2.TokenizeRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.TokenizeResponse.FromString,
                _registered_method=True)
        self.ChunkDocument = channel.unary_unary(
                '/memo.agent.TextProcessorService/ChunkDocument',
                request_serializer=proto_dot_agent__pb2.ChunkRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.ChunkResponse.FromString,
                _registered_method=True)
        self.RetrieveChunks = channel.unary_unary(
                '/memo.agent.TextProcessorService/RetrieveChunks',
                request_serializer=proto_dot_agent__pb2.RetrieveChunksRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.RetrieveChunksResponse.FromString,
                _registered_method=True)
        self.InvalidateCache = channel.unary_unary(
                '/memo.agent.TextProcessorService/InvalidateCache',
                request_serializer=proto_dot_agent__pb2.InvalidateCacheRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.InvalidateCacheResponse.FromString,
                _registered_method=True)
        self.TextHealthCheck = channel.unary_unary(
                '/memo.agent.TextProcessorService/TextHealthCheck',
                request_serializer=proto_dot_agent__pb2.HealthRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.IndexDocument = channel.unary_unary(
                '/memo.agent.TextProcessorService/IndexDocument',
                request_serializer=proto_dot_agent__pb2.IndexDocumentRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.IndexDocumentResponse.FromString,
                _registered_method=True)
        self.DeleteDocumentVectors = channel.unary_unary(
                '/memo.agent.TextProcessorService/DeleteDocumentVectors',
                request_serializer=proto_dot_agent__pb2.DeleteDocVectorsRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.DeleteDocVectorsResponse.FromString,
                _registered_method=True)
        self.DeleteKBCollection = channel.unary_unary(
                '/memo.agent.TextProcessorService/DeleteKBCollection',
                request_serializer=proto_dot_agent__pb2.DeleteKBCollectionRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.DeleteKBCollectionResponse.FromString,
                _registered_method=True)


class TextProcessorServiceServicer(object):
    """═══════════════════════════════════════════════════════════════════════════════
    TextProcessorService — CJK-aware text tokenization and document chunking
    ═══════════════════════════════════════════════════════════════════════════════

    """

    def Tokenize(self, request, context):
        """Tokenize text for BM25 indexing (CJK-aware segmentation with jieba).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChunkDocument(self, request, context):
        """Chunk document respecting markdown structure and sentence boundaries.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveChunks(self, request, context):
        """Hybrid retrieval: BM25 + vector search + RRF fusion.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidateCache(self, request, context):
        """Invalidate BM25 cache for a knowledge base.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TextHealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexDocument(self, request, context):
        """Index a document: chunk + embed + upsert to Qdrant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocumentVectors(self, request, context):
        """Delete all vectors for a document from Qdrant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKBCollection(self, request, context):
        """Delete entire Qdrant collection for a KB.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextProcessorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Tokenize': grpc.unary_unary_rpc_method_handler(
                    servicer.Tokenize,
                    request_deserializer=proto_dot_agent__pb2.TokenizeRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.TokenizeResponse.SerializeToString,
            ),
            'ChunkDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ChunkDocument,
                    request_deserializer=proto_dot_agent__pb2.ChunkRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.ChunkResponse.SerializeToString,
            ),
            'RetrieveChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveChunks,
                    request_deserializer=proto_dot_agent__pb2.RetrieveChunksRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.RetrieveChunksResponse.SerializeToString,
            ),
            'InvalidateCache': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateCache,
                    request_deserializer=proto_dot_agent__pb2.InvalidateCacheRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.InvalidateCacheResponse.SerializeToString,
            ),
            'TextHealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.TextHealthCheck,
                    request_deserializer=proto_dot_agent__pb2.HealthRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.HealthResponse.SerializeToString,
            ),
            'IndexDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexDocument,
                    request_deserializer=proto_dot_agent__pb2.IndexDocumentRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.IndexDocumentResponse.SerializeToString,
            ),
            'DeleteDocumentVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocumentVectors,
                    request_deserializer=proto_dot_agent__pb2.DeleteDocVectorsRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.DeleteDocVectorsResponse.SerializeToString,
            ),
            'DeleteKBCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKBCollection,
                    request_deserializer=proto_dot_agent__pb2.DeleteKBCollectionRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.DeleteKBCollectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memo.agent.TextProcessorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memo.agent.TextProcessorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextProcessorService(object):
    """═══════════════════════════════════════════════════════════════════════════════
    TextProcessorService — CJK-aware text tokenization and document chunking
    ═══════════════════════════════════════════════════════════════════════════════

    """

    @staticmethod
    def Tokenize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memo.agent.TextProcessorService/Tokenize',
            proto_dot_agent__pb2.TokenizeRequest.SerializeToString,
            proto_dot_agent__pb2.TokenizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChunkDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memo.agent.TextProcessorService/ChunkDocument',
            proto_dot_agent__pb2.ChunkRequest.SerializeToString,
            proto_dot_agent__pb2.ChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memo.agent.TextProcessorService/RetrieveChunks',
            proto_dot_agent__pb2.RetrieveChunksRequest.SerializeToString,
            proto_dot_agent__pb2.RetrieveChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvalidateCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memo.agent.TextProcessorService/InvalidateCache',
            proto_dot_agent__pb2.InvalidateCacheRequest.SerializeToString,
            proto_dot_agent__pb2.InvalidateCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TextHealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memo.agent.TextProcessorService/TextHealthCheck',
            proto_dot_agent__pb2.HealthRequest.SerializeToString,
            proto_dot_agent__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndexDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memo.agent.TextProcessorService/IndexDocument',
            proto_dot_agent__pb2.IndexDocumentRequest.SerializeToString,
            proto_dot_agent__pb2.IndexDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocumentVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memo.agent.TextProcessorService/DeleteDocumentVectors',
            proto_dot_agent__pb2.DeleteDocVectorsRequest.SerializeToString,
            proto_dot_agent__pb2.DeleteDocVectorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteKBCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memo.agent.TextProcessorService/DeleteKBCollection',
            proto_dot_agent__pb2.DeleteKBCollectionRequest.SerializeToString,
            proto_dot_agent__pb2.DeleteKBCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
